coverage:
  status:

    project:
      default:
        target: 85%

    patch:
      default:
        informational: true
ignore:
  - grafana_client/elements/_async/*
  - test/*
  - test/elements/*
