{% set data = load_setup_py_data(setup_file='conda/setup.py') %}
{% set version = data.get('version') %}

package:
  name: grafana-client
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python
    - requests
  run:
    - python
    - requests

test:
  imports:
    - grafana_client
    - grafana_client.elements

about:
  home: https://panodata.github.io/grafana-client/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Yet another Python library for Grafana API
  doc_url: https://panodata.github.io/grafana-client/
  dev_url: https://panodata.github.io/grafana-client/

#extra:
#  recipe-maintainers:
#    - m0nhawk
